version: "3.7"
services:
  app:
    build: ./my-view
    container_name: result-viewer
    restart: always
    environment: 
      - DB_HOST=mongodb
      - DB=url-shortner
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      mongodb_INITDB_DATABASE: myView
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
